Error in file(file, "rt") : cannot open the connection
Calls: CreateInfercnvObject -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'cellAnnotations_filtered_ST1R-Nuclei.txt': No such file or directory
Execution halted
